import {dateFormatter} from '../utils/dateFormatter';

export const newTripStateData = {
  type: "",
  fromCountry: "RW",
  fromCity: "",
  toCountry: "RW",
  toCity: "",
  stopCountry: "RW",
  stopCity: "",
  accommodation: "",
  arrivalDate:  dateFormatter(new Date()),
  departureDate: dateFormatter(new Date()) ,
  returnDate: dateFormatter(new Date()),
  secondDepartureDate: dateFormatter(new Date()),
  reason: "",
  message: "",
  stops: [],
  tripTypeError: "",
  fromCountryError: "",
  fromCityError: "",
  toCountryError: "",
  toCityError: "",
  stopCountryError: "",
  stopCityError: "",
  accommodationError: "",
  departureDateError: "",
  returnDateError: "",
  arrivalDateError: "",
  secondDepartureDateError: "",
  reasonError: "",

  returnDateStatus: false,
  arrivalDateErrorStatus: false,
  open: false,
  stopCountryErrorStatus: false,
  stopCityErrorStatus: false,
  tripTypeErrorStatus: false,
  fromCountryErrorStatus: false,
  fromCityErrorStatus: false,
  toCountryErrorStatus: false,
  toCityErrorStatus: false,
  accommodationErrorStatus: false,
  departureDateErrorStatus: false,
  returnDateErrorStatus: false,
  secondDepartureDateErrorStatus: false,
  reasonErrorStatus: false,
}

export const textFieldsValidator = {
  tripTypeError: "",
  fromCountryError: "",
  fromCityError: "",
  toCountryError: "",
  toCityError: "",
  accommodationError: "",
  departureDateError: "",
  secondDepartureDateError: "",
  returnDateError: "",
  arrivalDateError: "",
  reasonError: "",
  stopCountryError: "",
  stopCityError: "",

  open: false,
  returnDateStatus: false,
  arrivalDateErrorStatus: false,
  tripTypeErrorStatus: false,
  fromCountryErrorStatus: false,
  fromCityErrorStatus: false,
  toCountryErrorStatus: false,
  toCityErrorStatus: false,
  departureDateErrorStatus: false,
  returnDateErrorStatus: false,
  secondDepartureDateErrorStatus: false,
  accommodationErrorStatus: false,
  stopCountryErrorStatus: false,
  stopCityErrorStatus: false,
  reasonErrorStatus: false,
}

