export const ADD_ACCOMMODATION_REQUEST = "ADD_ACCOMMODATION_REQUEST";
export const GET_ACCOMMODATIONS = "GET_ACCOMMODATIONS";
export const GET_ACCOMMODATIONS_REQUEST = "GET_ACCOMMODATIONS_REQUEST";
export const ADD_ROOMS = "ADD_ROOMS";
export const VIEW_ALL_ACCOMMODATIONS = 'VIEW_ALL_ACCOMMODATIONS';
export const VIEW_ALL_ACCOMMODATIONS_SUCCESS = 'VIEW_ALL_ACCOMMODATIONS_SUCCESS';
export const VIEW_ALL_ACCOMMODATIONS_FAILURE = 'VIEW_ALL_ACCOMMODATIONS_FAILURE';

