export const ADD_LIKE_OR_DISLIKE_REQUEST = 'ADD_LIKE_OR_DISLIKE_REQUEST';
export const ADD_LIKE_DISLIKE_SUCCESS = 'ADD_LIKE_DISLIKE_SUCCESS';
export const ADD_LIKE_DISLIKE_FAILURE = 'ADD_LIKE_DISLIKE_FAILURE';

