export const NEW_TRIP_REQUEST = 'NEW_TRIP_REQUEST';
export const NEW_TRIP_REQUEST_SUCCESS = 'NEW_TRIP_REQUEST_SUCCESS';
export const NEW_TRIP_REQUEST_FAILURE = 'NEW_TRIP_REQUEST_FAILURE';
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';


